#!/bin/bash -eu
#
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Define the destination directory
LICENSE_DESTINATION="$HOME/Library/Application Support/ECLIPSA"

# Create the directory if it doesn't exist
mkdir -p "$LICENSE_DESTINATION"

# Copy the license file from the package to the destination
cp "$1/Contents/Resources/LICENSE.txt" "$LICENSE_DESTINATION/"

# Set appropriate permissions
chmod 644 "$LICENSE_DESTINATION/LICENSE.txt"

exit 0