/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
#include <map>
#include <string>

namespace LanguageData {
enum class MixLanguages {
  Undetermined,
  Multiple,
  Afar,
  Abkhazian,
  Afrikaans,
  Akan,
  Albanian,
  Amharic,
  Arabic,
  Aragonese,
  Armenian,
  Assamese,
  Avaric,
  Avestan,
  Aymara,
  Azerbaijani,
  Bashkir,
  Bambara,
  Basque,
  Belarusian,
  Bengali,
  Bislama,
  Bosnian,
  Breton,
  Bulgarian,
  Burmese,
  Catalan,
  Chamorro,
  Chechen,
  Chinese,
  Church,
  Chuvash,
  Cornish,
  Corsican,
  Cree,
  Czech,
  Danish,
  Divehi,
  Dutch,
  Dzongkha,
  English,
  Esperanto,
  Estonian,
  Ewe,
  Faroese,
  Fijian,
  Finnish,
  French,
  Western,
  Fulah,
  Georgian,
  German,
  Gaelic,
  Irish,
  Galician,
  Manx,
  Greek,
  Guarani,
  Gujarati,
  Haitian,
  Hausa,
  Hebrew,
  Herero,
  Hindi,
  Hiri,
  Croatian,
  Hungarian,
  Igbo,
  Icelandic,
  Ido,
  Sichuan,
  Inuktitut,
  Interlingue,
  Interlingua,
  Indonesian,
  Inupiaq,
  Italian,
  Javanese,
  Japanese,
  Kalaallisut,
  Kannada,
  Kashmiri,
  Kanuri,
  Kazakh,
  Central,
  Kikuyu,
  Kinyarwanda,
  Kirghiz,
  Komi,
  Kongo,
  Korean,
  Kuanyama,
  Kurdish,
  Lao,
  Latin,
  Latvian,
  Limburgan,
  Lingala,
  Lithuanian,
  Luxembourgish,
  Luba_Katanga,
  Ganda,
  Macedonian,
  Marshallese,
  Malayalam,
  Maori,
  Marathi,
  Malay,
  Malagasy,
  Maltese,
  Mongolian,
  Nauru,
  Navajo,
  South_Ndebele,
  North_Ndebele,
  Ndonga,
  Nepali,
  Norwegian_Nynorsk,
  Norwegian_Bokmal,
  Norwegian,
  Chichewa,
  Occitan,
  Ojibwa,
  Oriya,
  Oromo,
  Ossetian,
  Panjabi,
  Persian,
  Pali,
  Polish,
  Portuguese,
  Pushto,
  Quechua,
  Romansh,
  Romanian,
  Rundi,
  Russian,
  Sango,
  Sanskrit,
  Sinhala,
  Slovak,
  Slovenian,
  Northern_Sami,
  Samoan,
  Shona,
  Sindhi,
  Somali,
  Sotho,
  Spanish,
  Sardinian,
  Serbian,
  Swati,
  Sundanese,
  Swahili,
  Swedish,
  Tahitian,
  Tamil,
  Tatar,
  Telugu,
  Tajik,
  Tagalog,
  Thai,
  Tibetan,
  Tigrinya,
  Tonga,
  Tswana,
  Tsonga,
  Turkmen,
  Turkish,
  Twi,
  Uighur,
  Ukrainian,
  Urdu,
  Uzbek,
  Venda,
  Vietnamese,
  Volapuk,
  Welsh,
  Walloon,
  Wolof,
  Xhosa,
  Yiddish,
  Yoruba,
  Zhuang,
  Zulu,
  COUNT
};

const std::map<MixLanguages, std::pair<std::string, std::vector<std::string>>>
    langcodes_map = {
        {MixLanguages::Undetermined, {"und", {""}}},
        {MixLanguages::Multiple, {"mul", {"Multiple"}}},
        {MixLanguages::Afar, {"aar", {"Afar"}}},
        {MixLanguages::Abkhazian, {"abk", {"Abkhazian"}}},
        {MixLanguages::Afrikaans, {"afr", {"Afrikaans"}}},
        {MixLanguages::Akan, {"aka", {"Akan"}}},
        {MixLanguages::Albanian, {"alb", {"Albanian"}}},
        {MixLanguages::Amharic, {"amh", {"Amharic"}}},
        {MixLanguages::Arabic, {"ara", {"Arabic"}}},
        {MixLanguages::Aragonese, {"arg", {"Aragonese"}}},
        {MixLanguages::Armenian, {"arm", {"Armenian"}}},
        {MixLanguages::Assamese, {"asm", {"Assamese"}}},
        {MixLanguages::Avaric, {"ava", {"Avaric"}}},
        {MixLanguages::Avestan, {"ave", {"Avestan"}}},
        {MixLanguages::Aymara, {"aym", {"Aymara"}}},
        {MixLanguages::Azerbaijani, {"aze", {"Azerbaijani"}}},
        {MixLanguages::Bashkir, {"bak", {"Bashkir"}}},
        {MixLanguages::Bambara, {"bam", {"Bambara"}}},
        {MixLanguages::Basque, {"baq", {"Basque"}}},
        {MixLanguages::Belarusian, {"bel", {"Belarusian"}}},
        {MixLanguages::Bengali, {"ben", {"Bengali"}}},
        {MixLanguages::Bislama, {"bis", {"Bislama"}}},
        {MixLanguages::Bosnian, {"bos", {"Bosnian"}}},
        {MixLanguages::Breton, {"bre", {"Breton"}}},
        {MixLanguages::Bulgarian, {"bul", {"Bulgarian"}}},
        {MixLanguages::Burmese, {"bur", {"Burmese"}}},
        {MixLanguages::Catalan, {"cat", {"Catalan", "Valencian"}}},
        {MixLanguages::Chamorro, {"cha", {"Chamorro"}}},
        {MixLanguages::Chechen, {"che", {"Chechen"}}},
        {MixLanguages::Chinese, {"chi", {"Chinese"}}},
        {MixLanguages::Church,
         {"chu",
          {"Church Slavic", "Old Slavonic", "Church Slavonic", "Old Bulgarian",
           "Old Church Slavonic"}}},
        {MixLanguages::Chuvash, {"chv", {"Chuvash"}}},
        {MixLanguages::Cornish, {"cor", {"Cornish"}}},
        {MixLanguages::Corsican, {"cos", {"Corsican"}}},
        {MixLanguages::Cree, {"cre", {"Cree"}}},
        {MixLanguages::Czech, {"cze", {"Czech"}}},
        {MixLanguages::Danish, {"dan", {"Danish"}}},
        {MixLanguages::Divehi, {"div", {"Divehi", "Dhivehi", "Maldivian"}}},
        {MixLanguages::Dutch, {"dut", {"Dutch", "Flemish"}}},
        {MixLanguages::Dzongkha, {"dzo", {"Dzongkha"}}},
        {MixLanguages::English, {"eng", {"English"}}},
        {MixLanguages::Esperanto, {"epo", {"Esperanto"}}},
        {MixLanguages::Estonian, {"est", {"Estonian"}}},
        {MixLanguages::Ewe, {"ewe", {"Ewe"}}},
        {MixLanguages::Faroese, {"fao", {"Faroese"}}},
        {MixLanguages::Fijian, {"fij", {"Fijian"}}},
        {MixLanguages::Finnish, {"fin", {"Finnish"}}},
        {MixLanguages::French, {"fre", {"French"}}},
        {MixLanguages::Western, {"fry", {"Western Frisian"}}},
        {MixLanguages::Fulah, {"ful", {"Fulah"}}},
        {MixLanguages::Georgian, {"geo", {"Georgian"}}},
        {MixLanguages::German, {"ger", {"German"}}},
        {MixLanguages::Gaelic, {"gla", {"Gaelic", "Scottish Gaelic"}}},
        {MixLanguages::Irish, {"gle", {"Irish"}}},
        {MixLanguages::Galician, {"glg", {"Galician"}}},
        {MixLanguages::Manx, {"glv", {"Manx"}}},
        {MixLanguages::Greek, {"gre", {"Greek, Modern (1453-)"}}},
        {MixLanguages::Guarani, {"grn", {"Guarani"}}},
        {MixLanguages::Gujarati, {"guj", {"Gujarati"}}},
        {MixLanguages::Haitian, {"hat", {"Haitian", "Haitian Creole"}}},
        {MixLanguages::Hausa, {"hau", {"Hausa"}}},
        {MixLanguages::Hebrew, {"heb", {"Hebrew"}}},
        {MixLanguages::Herero, {"her", {"Herero"}}},
        {MixLanguages::Hindi, {"hin", {"Hindi"}}},
        {MixLanguages::Hiri, {"hmo", {"Hiri Motu"}}},
        {MixLanguages::Croatian, {"hrv", {"Croatian"}}},
        {MixLanguages::Hungarian, {"hun", {"Hungarian"}}},
        {MixLanguages::Igbo, {"ibo", {"Igbo"}}},
        {MixLanguages::Icelandic, {"ice", {"Icelandic"}}},
        {MixLanguages::Ido, {"ido", {"Ido"}}},
        {MixLanguages::Sichuan, {"iii", {"Sichuan Yi", "Nuosu"}}},
        {MixLanguages::Inuktitut, {"iku", {"Inuktitut"}}},
        {MixLanguages::Interlingue, {"ile", {"Interlingue", "Occidental"}}},
        {MixLanguages::Interlingua,
         {"ina",
          {"Interlingua (International Auxiliary Language Association)"}}},
        {MixLanguages::Indonesian, {"ind", {"Indonesian"}}},
        {MixLanguages::Inupiaq, {"ipk", {"Inupiaq"}}},
        {MixLanguages::Italian, {"ita", {"Italian"}}},
        {MixLanguages::Javanese, {"jav", {"Javanese"}}},
        {MixLanguages::Japanese, {"jpn", {"Japanese"}}},
        {MixLanguages::Kalaallisut, {"kal", {"Kalaallisut", "Greenlandic"}}},
        {MixLanguages::Kannada, {"kan", {"Kannada"}}},
        {MixLanguages::Kashmiri, {"kas", {"Kashmiri"}}},
        {MixLanguages::Kanuri, {"kau", {"Kanuri"}}},
        {MixLanguages::Kazakh, {"kaz", {"Kazakh"}}},
        {MixLanguages::Central, {"khm", {"Central Khmer"}}},
        {MixLanguages::Kikuyu, {"kik", {"Kikuyu", "Gikuyu"}}},
        {MixLanguages::Kinyarwanda, {"kin", {"Kinyarwanda"}}},
        {MixLanguages::Kirghiz, {"kir", {"Kirghiz", "Kyrgyz"}}},
        {MixLanguages::Komi, {"kom", {"Komi"}}},
        {MixLanguages::Kongo, {"kon", {"Kongo"}}},
        {MixLanguages::Korean, {"kor", {"Korean"}}},
        {MixLanguages::Kuanyama, {"kua", {"Kuanyama", "Kwanyama"}}},
        {MixLanguages::Kurdish, {"kur", {"Kurdish"}}},
        {MixLanguages::Lao, {"lao", {"Lao"}}},
        {MixLanguages::Latin, {"lat", {"Latin"}}},
        {MixLanguages::Latvian, {"lav", {"Latvian"}}},
        {MixLanguages::Limburgan,
         {"lim", {"Limburgan", "Limburger", "Limburgish"}}},
        {MixLanguages::Lingala, {"lin", {"Lingala"}}},
        {MixLanguages::Lithuanian, {"lit", {"Lithuanian"}}},
        {MixLanguages::Luxembourgish,
         {"ltz", {"Luxembourgish", "Letzeburgesch"}}},
        {MixLanguages::Luba_Katanga, {"lub", {"Luba-Katanga"}}},
        {MixLanguages::Ganda, {"lug", {"Ganda"}}},
        {MixLanguages::Macedonian, {"mac", {"Macedonian"}}},
        {MixLanguages::Marshallese, {"mah", {"Marshallese"}}},
        {MixLanguages::Malayalam, {"mal", {"Malayalam"}}},
        {MixLanguages::Maori, {"mao", {"Maori"}}},
        {MixLanguages::Marathi, {"mar", {"Marathi"}}},
        {MixLanguages::Malay, {"may", {"Malay"}}},
        {MixLanguages::Malagasy, {"mlg", {"Malagasy"}}},
        {MixLanguages::Maltese, {"mlt", {"Maltese"}}},
        {MixLanguages::Mongolian, {"mon", {"Mongolian"}}},
        {MixLanguages::Nauru, {"nau", {"Nauru"}}},
        {MixLanguages::Navajo, {"nav", {"Navajo", "Navaho"}}},
        {MixLanguages::South_Ndebele, {"nbl", {"South Ndebele"}}},
        {MixLanguages::North_Ndebele, {"nde", {"North Ndebele"}}},
        {MixLanguages::Ndonga, {"ndo", {"Ndonga"}}},
        {MixLanguages::Nepali, {"nep", {"Nepali"}}},
        {MixLanguages::Norwegian_Nynorsk, {"nno", {"Norwegian Nynorsk"}}},
        {MixLanguages::Norwegian_Bokmal, {"nob", {"Norwegian Bokmal"}}},
        {MixLanguages::Norwegian, {"nor", {"Norwegian"}}},
        {MixLanguages::Chichewa, {"nya", {"Chichewa", "Chewa", "Nyanja"}}},
        {MixLanguages::Occitan, {"oci", {"Occitan (post 1500)"}}},
        {MixLanguages::Ojibwa, {"oji", {"Ojibwa"}}},
        {MixLanguages::Oriya, {"ori", {"Oriya"}}},
        {MixLanguages::Oromo, {"orm", {"Oromo"}}},
        {MixLanguages::Ossetian, {"oss", {"Ossetian", "Ossetic"}}},
        {MixLanguages::Panjabi, {"pan", {"Panjabi", "Punjabi"}}},
        {MixLanguages::Persian, {"per", {"Persian"}}},
        {MixLanguages::Pali, {"pli", {"Pali"}}},
        {MixLanguages::Polish, {"pol", {"Polish"}}},
        {MixLanguages::Portuguese, {"por", {"Portuguese"}}},
        {MixLanguages::Pushto, {"pus", {"Pushto", "Pashto"}}},
        {MixLanguages::Quechua, {"que", {"Quechua"}}},
        {MixLanguages::Romansh, {"roh", {"Romansh"}}},
        {MixLanguages::Romanian,
         {"rum", {"Romanian", "Moldavian", "Moldovan"}}},
        {MixLanguages::Rundi, {"run", {"Rundi"}}},
        {MixLanguages::Russian, {"rus", {"Russian"}}},
        {MixLanguages::Sango, {"sag", {"Sango"}}},
        {MixLanguages::Sanskrit, {"san", {"Sanskrit"}}},
        {MixLanguages::Sinhala, {"sin", {"Sinhala", "Sinhalese"}}},
        {MixLanguages::Slovak, {"slo", {"Slovak"}}},
        {MixLanguages::Slovenian, {"slv", {"Slovenian"}}},
        {MixLanguages::Northern_Sami, {"sme", {"Northern Sami"}}},
        {MixLanguages::Samoan, {"smo", {"Samoan"}}},
        {MixLanguages::Shona, {"sna", {"Shona"}}},
        {MixLanguages::Sindhi, {"snd", {"Sindhi"}}},
        {MixLanguages::Somali, {"som", {"Somali"}}},
        {MixLanguages::Sotho, {"sot", {"Sotho, Southern"}}},
        {MixLanguages::Spanish, {"spa", {"Spanish", "Castilian"}}},
        {MixLanguages::Sardinian, {"srd", {"Sardinian"}}},
        {MixLanguages::Serbian, {"srp", {"Serbian"}}},
        {MixLanguages::Swati, {"ssw", {"Swati"}}},
        {MixLanguages::Sundanese, {"sun", {"Sundanese"}}},
        {MixLanguages::Swahili, {"swa", {"Swahili"}}},
        {MixLanguages::Swedish, {"swe", {"Swedish"}}},
        {MixLanguages::Tahitian, {"tah", {"Tahitian"}}},
        {MixLanguages::Tamil, {"tam", {"Tamil"}}},
        {MixLanguages::Tatar, {"tat", {"Tatar"}}},
        {MixLanguages::Telugu, {"tel", {"Telugu"}}},
        {MixLanguages::Tajik, {"tgk", {"Tajik"}}},
        {MixLanguages::Tagalog, {"tgl", {"Tagalog"}}},
        {MixLanguages::Thai, {"tha", {"Thai"}}},
        {MixLanguages::Tibetan, {"tib", {"Tibetan"}}},
        {MixLanguages::Tigrinya, {"tir", {"Tigrinya"}}},
        {MixLanguages::Tonga, {"ton", {"Tonga (Tonga Islands)"}}},
        {MixLanguages::Tswana, {"tsn", {"Tswana"}}},
        {MixLanguages::Tsonga, {"tso", {"Tsonga"}}},
        {MixLanguages::Turkmen, {"tuk", {"Turkmen"}}},
        {MixLanguages::Turkish, {"tur", {"Turkish"}}},
        {MixLanguages::Twi, {"twi", {"Twi"}}},
        {MixLanguages::Uighur, {"uig", {"Uighur", "Uyghur"}}},
        {MixLanguages::Ukrainian, {"ukr", {"Ukrainian"}}},
        {MixLanguages::Urdu, {"urd", {"Urdu"}}},
        {MixLanguages::Uzbek, {"uzb", {"Uzbek"}}},
        {MixLanguages::Venda, {"ven", {"Venda"}}},
        {MixLanguages::Vietnamese, {"vie", {"Vietnamese"}}},
        {MixLanguages::Volapuk, {"vol", {"Volapuk"}}},
        {MixLanguages::Welsh, {"wel", {"Welsh"}}},
        {MixLanguages::Walloon, {"wln", {"Walloon"}}},
        {MixLanguages::Wolof, {"wol", {"Wolof"}}},
        {MixLanguages::Xhosa, {"xho", {"Xhosa"}}},
        {MixLanguages::Yiddish, {"yid", {"Yiddish"}}},
        {MixLanguages::Yoruba, {"yor", {"Yoruba"}}},
        {MixLanguages::Zhuang, {"zha", {"Zhuang", "Chuang"}}},
        {MixLanguages::Zulu, {"zul", {"Zulu"}}},
};

const std::map<std::string, MixLanguages> langvector_map = {
    {"", MixLanguages::Undetermined},
    {"Multiple", MixLanguages::Multiple},
    {"Afar", MixLanguages::Afar},
    {"Abkhazian", MixLanguages::Abkhazian},
    {"Afrikaans", MixLanguages::Afrikaans},
    {"Akan", MixLanguages::Akan},
    {"Albanian", MixLanguages::Albanian},
    {"Amharic", MixLanguages::Amharic},
    {"Arabic", MixLanguages::Arabic},
    {"Aragonese", MixLanguages::Aragonese},
    {"Armenian", MixLanguages::Armenian},
    {"Assamese", MixLanguages::Assamese},
    {"Avaric", MixLanguages::Avaric},
    {"Avestan", MixLanguages::Avestan},
    {"Aymara", MixLanguages::Aymara},
    {"Azerbaijani", MixLanguages::Azerbaijani},
    {"Bashkir", MixLanguages::Bashkir},
    {"Bambara", MixLanguages::Bambara},
    {"Basque", MixLanguages::Basque},
    {"Belarusian", MixLanguages::Belarusian},
    {"Bengali", MixLanguages::Bengali},
    {"Bislama", MixLanguages::Bislama},
    {"Bosnian", MixLanguages::Bosnian},
    {"Breton", MixLanguages::Breton},
    {"Bulgarian", MixLanguages::Bulgarian},
    {"Burmese", MixLanguages::Burmese},
    {"Catalan", MixLanguages::Catalan},
    {"Valencian", MixLanguages::Catalan},
    {"Chamorro", MixLanguages::Chamorro},
    {"Chechen", MixLanguages::Chechen},
    {"Chinese", MixLanguages::Chinese},
    {"Church Slavic", MixLanguages::Church},
    {"Old Slavonic", MixLanguages::Church},
    {"Church Slavonic", MixLanguages::Church},
    {"Old Bulgarian", MixLanguages::Church},
    {"Old Church Slavonic", MixLanguages::Church},
    {"Chuvash", MixLanguages::Chuvash},
    {"Cornish", MixLanguages::Cornish},
    {"Corsican", MixLanguages::Corsican},
    {"Cree", MixLanguages::Cree},
    {"Czech", MixLanguages::Czech},
    {"Danish", MixLanguages::Danish},
    {"Divehi", MixLanguages::Divehi},
    {"Dhivehi", MixLanguages::Divehi},
    {"Maldivian", MixLanguages::Divehi},
    {"Dutch", MixLanguages::Dutch},
    {"Flemish", MixLanguages::Dutch},
    {"Dzongkha", MixLanguages::Dzongkha},
    {"English", MixLanguages::English},
    {"Esperanto", MixLanguages::Esperanto},
    {"Estonian", MixLanguages::Estonian},
    {"Ewe", MixLanguages::Ewe},
    {"Faroese", MixLanguages::Faroese},
    {"Fijian", MixLanguages::Fijian},
    {"Finnish", MixLanguages::Finnish},
    {"French", MixLanguages::French},
    {"Western Frisian", MixLanguages::Western},
    {"Fulah", MixLanguages::Fulah},
    {"Georgian", MixLanguages::Georgian},
    {"German", MixLanguages::German},
    {"Gaelic", MixLanguages::Gaelic},
    {"Scottish Gaelic", MixLanguages::Gaelic},
    {"Irish", MixLanguages::Irish},
    {"Galician", MixLanguages::Galician},
    {"Manx", MixLanguages::Manx},
    {"Greek", MixLanguages::Greek},
    {"Modern (1453-)", MixLanguages::Greek},
    {"Guarani", MixLanguages::Guarani},
    {"Gujarati", MixLanguages::Gujarati},
    {"Haitian", MixLanguages::Haitian},
    {"Haitian Creole", MixLanguages::Haitian},
    {"Hausa", MixLanguages::Hausa},
    {"Hebrew", MixLanguages::Hebrew},
    {"Herero", MixLanguages::Herero},
    {"Hindi", MixLanguages::Hindi},
    {"Hiri Motu", MixLanguages::Hiri},
    {"Croatian", MixLanguages::Croatian},
    {"Hungarian", MixLanguages::Hungarian},
    {"Igbo", MixLanguages::Igbo},
    {"Icelandic", MixLanguages::Icelandic},
    {"Ido", MixLanguages::Ido},
    {"Sichuan Yi", MixLanguages::Sichuan},
    {"Nuosu", MixLanguages::Sichuan},
    {"Inuktitut", MixLanguages::Inuktitut},
    {"Interlingue", MixLanguages::Interlingue},
    {"Occidental", MixLanguages::Interlingue},
    {"Interlingua (International Auxiliary Language Association)",
     MixLanguages::Interlingua},
    {"Indonesian", MixLanguages::Indonesian},
    {"Inupiaq", MixLanguages::Inupiaq},
    {"Italian", MixLanguages::Italian},
    {"Javanese", MixLanguages::Javanese},
    {"Japanese", MixLanguages::Japanese},
    {"Kalaallisut", MixLanguages::Kalaallisut},
    {"Greenlandic", MixLanguages::Kalaallisut},
    {"Kannada", MixLanguages::Kannada},
    {"Kashmiri", MixLanguages::Kashmiri},
    {"Kanuri", MixLanguages::Kanuri},
    {"Kazakh", MixLanguages::Kazakh},
    {"Central Khmer", MixLanguages::Central},
    {"Kikuyu", MixLanguages::Kikuyu},
    {"Gikuyu", MixLanguages::Kikuyu},
    {"Kinyarwanda", MixLanguages::Kinyarwanda},
    {"Kirghiz", MixLanguages::Kirghiz},
    {"Kyrgyz", MixLanguages::Kirghiz},
    {"Komi", MixLanguages::Komi},
    {"Kongo", MixLanguages::Kongo},
    {"Korean", MixLanguages::Korean},
    {"Kuanyama", MixLanguages::Kuanyama},
    {"Kwanyama", MixLanguages::Kuanyama},
    {"Kurdish", MixLanguages::Kurdish},
    {"Lao", MixLanguages::Lao},
    {"Latin", MixLanguages::Latin},
    {"Latvian", MixLanguages::Latvian},
    {"Limburgan", MixLanguages::Limburgan},
    {"Limburger", MixLanguages::Limburgan},
    {"Limburgish", MixLanguages::Limburgan},
    {"Lingala", MixLanguages::Lingala},
    {"Lithuanian", MixLanguages::Lithuanian},
    {"Luxembourgish", MixLanguages::Luxembourgish},
    {"Letzeburgesch", MixLanguages::Luxembourgish},
    {"Luba-Katanga", MixLanguages::Luba_Katanga},
    {"Ganda", MixLanguages::Ganda},
    {"Macedonian", MixLanguages::Macedonian},
    {"Marshallese", MixLanguages::Marshallese},
    {"Malayalam", MixLanguages::Malayalam},
    {"Maori", MixLanguages::Maori},
    {"Marathi", MixLanguages::Marathi},
    {"Malay", MixLanguages::Malay},
    {"Malagasy", MixLanguages::Malagasy},
    {"Maltese", MixLanguages::Maltese},
    {"Mongolian", MixLanguages::Mongolian},
    {"Nauru", MixLanguages::Nauru},
    {"Navajo", MixLanguages::Navajo},
    {"Navaho", MixLanguages::Navajo},
    {"South Ndebele", MixLanguages::South_Ndebele},
    {"North Ndebele", MixLanguages::North_Ndebele},
    {"Ndonga", MixLanguages::Ndonga},
    {"Nepali", MixLanguages::Nepali},
    {"Norwegian Nynorsk", MixLanguages::Norwegian_Nynorsk},
    {"Norwegian Bokmal", MixLanguages::Norwegian_Bokmal},
    {"Norwegian", MixLanguages::Norwegian},
    {"Chichewa", MixLanguages::Chichewa},
    {"Chewa", MixLanguages::Chichewa},
    {"Nyanja", MixLanguages::Chichewa},
    {"Occitan (post 1500)", MixLanguages::Occitan},
    {"Ojibwa", MixLanguages::Ojibwa},
    {"Oriya", MixLanguages::Oriya},
    {"Oromo", MixLanguages::Oromo},
    {"Ossetian", MixLanguages::Ossetian},
    {"Ossetic", MixLanguages::Ossetian},
    {"Panjabi", MixLanguages::Panjabi},
    {"Punjabi", MixLanguages::Panjabi},
    {"Persian", MixLanguages::Persian},
    {"Pali", MixLanguages::Pali},
    {"Polish", MixLanguages::Polish},
    {"Portuguese", MixLanguages::Portuguese},
    {"Pushto", MixLanguages::Pushto},
    {"Pashto", MixLanguages::Pushto},
    {"Quechua", MixLanguages::Quechua},
    {"Romansh", MixLanguages::Romansh},
    {"Romanian", MixLanguages::Romanian},
    {"Moldavian", MixLanguages::Romanian},
    {"Moldovan", MixLanguages::Romanian},
    {"Rundi", MixLanguages::Rundi},
    {"Russian", MixLanguages::Russian},
    {"Sango", MixLanguages::Sango},
    {"Sanskrit", MixLanguages::Sanskrit},
    {"Sinhala", MixLanguages::Sinhala},
    {"Sinhalese", MixLanguages::Sinhala},
    {"Slovak", MixLanguages::Slovak},
    {"Slovenian", MixLanguages::Slovenian},
    {"Northern Sami", MixLanguages::Northern_Sami},
    {"Samoan", MixLanguages::Samoan},
    {"Shona", MixLanguages::Shona},
    {"Sindhi", MixLanguages::Sindhi},
    {"Somali", MixLanguages::Somali},
    {"Southern Sotho", MixLanguages::Sotho},
    {"Spanish", MixLanguages::Spanish},
    {"Castilian", MixLanguages::Spanish},
    {"Sardinian", MixLanguages::Sardinian},
    {"Serbian", MixLanguages::Serbian},
    {"Swati", MixLanguages::Swati},
    {"Sundanese", MixLanguages::Sundanese},
    {"Swahili", MixLanguages::Swahili},
    {"Swedish", MixLanguages::Swedish},
    {"Tahitian", MixLanguages::Tahitian},
    {"Tamil", MixLanguages::Tamil},
    {"Tatar", MixLanguages::Tatar},
    {"Telugu", MixLanguages::Telugu},
    {"Tajik", MixLanguages::Tajik},
    {"Tagalog", MixLanguages::Tagalog},
    {"Thai", MixLanguages::Thai},
    {"Tibetan", MixLanguages::Tibetan},
    {"Tigrinya", MixLanguages::Tigrinya},
    {"Tonga (Tonga Islands)", MixLanguages::Tonga},
    {"Tswana", MixLanguages::Tswana},
    {"Tsonga", MixLanguages::Tsonga},
    {"Turkmen", MixLanguages::Turkmen},
    {"Turkish", MixLanguages::Turkish},
    {"Twi", MixLanguages::Twi},
    {"Uighur", MixLanguages::Uighur},
    {"Uyghur", MixLanguages::Uighur},
    {"Ukrainian", MixLanguages::Ukrainian},
    {"Urdu", MixLanguages::Urdu},
    {"Uzbek", MixLanguages::Uzbek},
    {"Venda", MixLanguages::Venda},
    {"Vietnamese", MixLanguages::Vietnamese},
    {"Volapuk", MixLanguages::Volapuk},
    {"Welsh", MixLanguages::Welsh},
    {"Walloon", MixLanguages::Walloon},
    {"Wolof", MixLanguages::Wolof},
    {"Xhosa", MixLanguages::Xhosa},
    {"Yiddish", MixLanguages::Yiddish},
    {"Yoruba", MixLanguages::Yoruba},
    {"Zhuang", MixLanguages::Zhuang},
    {"Chuang", MixLanguages::Zhuang},
    {"Zulu", MixLanguages::Zulu}};

std::string getLanguageCode(const MixLanguages& language);

MixLanguages getLanguageEnum(const std::string& language);

std::string getLanguageName(const MixLanguages& language);

}  // namespace LanguageData
